sonar.projectKey=reckonna
sonar.projectName=Reckonna (Accounting CQRS)
sonar.host.url=https://sonar.thee5176.com
sonar.sources=cmd,internal,app,components,infra
sonar.tests=.
sonar.test.inclusions=**/*_test.go,**/*.test.ts,**/*.test.tsx,e2e/**
sonar.go.coverage.reportPaths=coverage.out
sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.exclusions=**/*_gen.go,**/mocks/**,**/node_modules/**,**/.terraform/**
