-- 003_seed_account.up.sql — GENERATED by scripts/gen-coa from config/coa.yaml.
-- Do not hand-edit; change config/coa.yaml and run `make gen-coa`. (plan 03 S5b)
INSERT INTO account (code, name, description, type, normal_balance, postable, current_noncurrent, ifrs_line_item, allowed_books, required_dimensions, status, owner) VALUES
  (10000, 'Cash and cash equivalents', 'Cash on hand and demand deposits; excludes restricted or term deposits.', 'asset', 'debit', true, 'current', 'Cash and cash equivalents', '{"base"}', '{}', 'active', 'COA Steward'),
  (11000, 'Trade and other receivables', 'Amounts owed by customers and other short-term receivables.', 'asset', 'debit', true, 'current', 'Trade and other receivables', '{"base"}', '{}', 'active', 'COA Steward'),
  (12000, 'Prepayments', 'Payments made in advance for goods or services not yet received.', 'asset', 'debit', true, 'current', 'Prepayments', '{"base"}', '{}', 'active', 'COA Steward'),
  (14000, 'Property, plant and equipment', 'Tangible assets held for use over more than one period, net of depreciation.', 'asset', 'debit', true, 'non_current', 'Property, plant and equipment', '{"base"}', '{}', 'active', 'COA Steward'),
  (14500, 'Intangible assets', 'Identifiable non-monetary assets without physical substance, net of amortisation.', 'asset', 'debit', true, 'non_current', 'Intangible assets', '{"base"}', '{}', 'active', 'COA Steward'),
  (20000, 'Trade and other payables', 'Amounts owed to suppliers and other short-term payables.', 'liability', 'credit', true, 'current', 'Trade and other payables', '{"base"}', '{}', 'active', 'COA Steward'),
  (21000, 'Accrued expenses', 'Expenses incurred but not yet invoiced or paid at period end.', 'liability', 'credit', true, 'current', 'Trade and other payables', '{"base"}', '{}', 'active', 'COA Steward'),
  (21500, 'Customer escrow payable', 'Buyer funds held in escrow before release to the seller; a liability to the customer.', 'liability', 'credit', true, 'current', 'Other payables', '{"base"}', '{"counterparty"}', 'active', 'COA Steward'),
  (24000, 'Lease liabilities', 'Obligations under lease contracts due beyond one year.', 'liability', 'credit', true, 'non_current', 'Lease liabilities', '{"base"}', '{}', 'active', 'COA Steward'),
  (30000, 'Contributed capital', 'Capital contributed by owners in exchange for equity.', 'equity', 'credit', true, NULL, 'Issued capital', '{"base"}', '{}', 'active', 'COA Steward'),
  (31000, 'Retained earnings', 'Cumulative net income retained rather than distributed.', 'equity', 'credit', true, NULL, 'Retained earnings', '{"base"}', '{}', 'active', 'COA Steward'),
  (40000, 'Service / fee revenue', 'Revenue earned from rendering services or charging fees.', 'income', 'credit', true, NULL, 'Revenue', '{"base"}', '{}', 'active', 'COA Steward'),
  (50000, 'Cost of services', 'Costs directly attributable to delivering services.', 'expense', 'debit', true, NULL, 'Cost of sales', '{"base"}', '{}', 'active', 'COA Steward'),
  (60000, 'Staff costs', 'Wages, salaries, and related employee benefit expenses.', 'expense', 'debit', true, NULL, 'Employee benefits expense', '{"base"}', '{}', 'active', 'COA Steward'),
  (61000, 'Marketing and advertising', 'Costs of promoting the business and its services.', 'expense', 'debit', true, NULL, 'Other expenses', '{"base"}', '{}', 'active', 'COA Steward'),
  (62000, 'General and administrative', 'Overhead and administrative costs not tied to service delivery.', 'expense', 'debit', true, NULL, 'Other expenses', '{"base"}', '{}', 'active', 'COA Steward'),
  (63000, 'Depreciation and amortisation', 'Systematic allocation of the cost of long-lived assets over their useful lives.', 'expense', 'debit', true, NULL, 'Depreciation and amortisation expense', '{"base"}', '{}', 'active', 'COA Steward'),
  (70000, 'Finance income', 'Interest and other income earned on financial assets.', 'income', 'credit', true, NULL, 'Finance income', '{"base"}', '{}', 'active', 'COA Steward'),
  (71000, 'Finance costs', 'Interest and other costs incurred on financial liabilities.', 'expense', 'debit', true, NULL, 'Finance costs', '{"base"}', '{}', 'active', 'COA Steward'),
  (80000, 'Income tax expense', 'Current and deferred income tax charged for the period.', 'expense', 'debit', true, NULL, 'Income tax expense', '{"base"}', '{}', 'active', 'COA Steward');
