// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: coa.sql

package query

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getOutstandingBalances = `-- name: GetOutstandingBalances :many
SELECT a.code AS account_code,
       a.name AS account_name,
       a.normal_balance,
       COALESCE(SUM(jl.amount) FILTER (WHERE jl.side = 'debit'),  0)::numeric  AS total_debit,
       COALESCE(SUM(jl.amount) FILTER (WHERE jl.side = 'credit'), 0)::numeric  AS total_credit
FROM account a
LEFT JOIN journal_line  jl ON jl.account_id = a.id
LEFT JOIN journal_entry je ON je.id = jl.journal_entry_id AND je.owner_sub = $1
WHERE a.code = ANY($2::int[])
GROUP BY a.code, a.name, a.normal_balance
ORDER BY a.code
`

type GetOutstandingBalancesParams struct {
	OwnerSub string  `json:"owner_sub"`
	Codes    []int32 `json:"codes"`
}

type GetOutstandingBalancesRow struct {
	AccountCode   int32          `json:"account_code"`
	AccountName   string         `json:"account_name"`
	NormalBalance NormalBalance  `json:"normal_balance"`
	TotalDebit    pgtype.Numeric `json:"total_debit"`
	TotalCredit   pgtype.Numeric `json:"total_credit"`
}

// Debit/credit totals per requested account, scoped to the caller's entries.
// LEFT JOINs keep requested accounts that have no postings (zero totals).
func (q *Queries) GetOutstandingBalances(ctx context.Context, arg GetOutstandingBalancesParams) ([]GetOutstandingBalancesRow, error) {
	rows, err := q.db.Query(ctx, getOutstandingBalances, arg.OwnerSub, arg.Codes)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetOutstandingBalancesRow{}
	for rows.Next() {
		var i GetOutstandingBalancesRow
		if err := rows.Scan(
			&i.AccountCode,
			&i.AccountName,
			&i.NormalBalance,
			&i.TotalDebit,
			&i.TotalCredit,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAccounts = `-- name: ListAccounts :many

SELECT code, name, description, type, normal_balance, postable, current_noncurrent, ifrs_line_item, status
FROM account
WHERE status = 'active'
ORDER BY code
`

type ListAccountsRow struct {
	Code              int32              `json:"code"`
	Name              string             `json:"name"`
	Description       string             `json:"description"`
	Type              AccountType        `json:"type"`
	NormalBalance     NormalBalance      `json:"normal_balance"`
	Postable          bool               `json:"postable"`
	CurrentNoncurrent *CurrentNoncurrent `json:"current_noncurrent"`
	IfrsLineItem      string             `json:"ifrs_line_item"`
	Status            AccountStatus      `json:"status"`
}

// Query-side chart-of-accounts + outstanding balances. SELECT ONLY.
func (q *Queries) ListAccounts(ctx context.Context) ([]ListAccountsRow, error) {
	rows, err := q.db.Query(ctx, listAccounts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAccountsRow{}
	for rows.Next() {
		var i ListAccountsRow
		if err := rows.Scan(
			&i.Code,
			&i.Name,
			&i.Description,
			&i.Type,
			&i.NormalBalance,
			&i.Postable,
			&i.CurrentNoncurrent,
			&i.IfrsLineItem,
			&i.Status,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
