// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: journal_entry.sql

package query

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const getJournalEntry = `-- name: GetJournalEntry :one

SELECT id, entry_date, description, owner_sub, book_id, version, created_at, updated_at
FROM journal_entry
WHERE id = $1 AND owner_sub = $2
`

type GetJournalEntryParams struct {
	ID       uuid.UUID `json:"id"`
	OwnerSub string    `json:"owner_sub"`
}

type GetJournalEntryRow struct {
	ID          uuid.UUID `json:"id"`
	EntryDate   time.Time `json:"entry_date"`
	Description string    `json:"description"`
	OwnerSub    string    `json:"owner_sub"`
	BookID      uuid.UUID `json:"book_id"`
	Version     int32     `json:"version"`
	CreatedAt   time.Time `json:"created_at"`
	UpdatedAt   time.Time `json:"updated_at"`
}

// Query-side reads. SELECT ONLY — this package is imported by cmd/query, which
// must have NO write path (IT9). Every read is scoped by owner_sub so one
// owner never sees another's rows (AT3, IT5).
func (q *Queries) GetJournalEntry(ctx context.Context, arg GetJournalEntryParams) (GetJournalEntryRow, error) {
	row := q.db.QueryRow(ctx, getJournalEntry, arg.ID, arg.OwnerSub)
	var i GetJournalEntryRow
	err := row.Scan(
		&i.ID,
		&i.EntryDate,
		&i.Description,
		&i.OwnerSub,
		&i.BookID,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getJournalLines = `-- name: GetJournalLines :many
SELECT jl.id, jl.journal_entry_id, a.code AS account_code, jl.side, jl.amount, jl.line_no
FROM journal_line jl
JOIN account a ON a.id = jl.account_id
JOIN journal_entry je ON je.id = jl.journal_entry_id
WHERE jl.journal_entry_id = $1 AND je.owner_sub = $2
ORDER BY jl.line_no
`

type GetJournalLinesParams struct {
	EntryID  uuid.UUID `json:"entry_id"`
	OwnerSub string    `json:"owner_sub"`
}

type GetJournalLinesRow struct {
	ID             uuid.UUID      `json:"id"`
	JournalEntryID uuid.UUID      `json:"journal_entry_id"`
	AccountCode    int32          `json:"account_code"`
	Side           EntrySide      `json:"side"`
	Amount         pgtype.Numeric `json:"amount"`
	LineNo         int32          `json:"line_no"`
}

// Lines of one entry, owner-scoped via the parent entry.
func (q *Queries) GetJournalLines(ctx context.Context, arg GetJournalLinesParams) ([]GetJournalLinesRow, error) {
	rows, err := q.db.Query(ctx, getJournalLines, arg.EntryID, arg.OwnerSub)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetJournalLinesRow{}
	for rows.Next() {
		var i GetJournalLinesRow
		if err := rows.Scan(
			&i.ID,
			&i.JournalEntryID,
			&i.AccountCode,
			&i.Side,
			&i.Amount,
			&i.LineNo,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listJournalEntries = `-- name: ListJournalEntries :many
SELECT id, entry_date, description, owner_sub, book_id, version, created_at, updated_at
FROM journal_entry
WHERE owner_sub = $1
  AND ($2::uuid IS NULL OR id > $2::uuid)
ORDER BY id ASC
LIMIT $3
`

type ListJournalEntriesParams struct {
	OwnerSub  string      `json:"owner_sub"`
	Cursor    pgtype.UUID `json:"cursor"`
	PageLimit int32       `json:"page_limit"`
}

type ListJournalEntriesRow struct {
	ID          uuid.UUID `json:"id"`
	EntryDate   time.Time `json:"entry_date"`
	Description string    `json:"description"`
	OwnerSub    string    `json:"owner_sub"`
	BookID      uuid.UUID `json:"book_id"`
	Version     int32     `json:"version"`
	CreatedAt   time.Time `json:"created_at"`
	UpdatedAt   time.Time `json:"updated_at"`
}

// Cursor pagination on the time-ordered UUIDv7 PK. A NULL cursor starts at the
// first page; the handler asks for limit+1 rows to compute has_more.
func (q *Queries) ListJournalEntries(ctx context.Context, arg ListJournalEntriesParams) ([]ListJournalEntriesRow, error) {
	rows, err := q.db.Query(ctx, listJournalEntries, arg.OwnerSub, arg.Cursor, arg.PageLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListJournalEntriesRow{}
	for rows.Next() {
		var i ListJournalEntriesRow
		if err := rows.Scan(
			&i.ID,
			&i.EntryDate,
			&i.Description,
			&i.OwnerSub,
			&i.BookID,
			&i.Version,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
