// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package query

import (
	"database/sql/driver"
	"fmt"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type AccountStatus string

const (
	AccountStatusActive   AccountStatus = "active"
	AccountStatusInactive AccountStatus = "inactive"
	AccountStatusArchived AccountStatus = "archived"
)

func (e *AccountStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = AccountStatus(s)
	case string:
		*e = AccountStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for AccountStatus: %T", src)
	}
	return nil
}

type NullAccountStatus struct {
	AccountStatus AccountStatus `json:"account_status"`
	Valid         bool          `json:"valid"` // Valid is true if AccountStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullAccountStatus) Scan(value interface{}) error {
	if value == nil {
		ns.AccountStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.AccountStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullAccountStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.AccountStatus), nil
}

type AccountType string

const (
	AccountTypeAsset     AccountType = "asset"
	AccountTypeLiability AccountType = "liability"
	AccountTypeEquity    AccountType = "equity"
	AccountTypeIncome    AccountType = "income"
	AccountTypeExpense   AccountType = "expense"
)

func (e *AccountType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = AccountType(s)
	case string:
		*e = AccountType(s)
	default:
		return fmt.Errorf("unsupported scan type for AccountType: %T", src)
	}
	return nil
}

type NullAccountType struct {
	AccountType AccountType `json:"account_type"`
	Valid       bool        `json:"valid"` // Valid is true if AccountType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullAccountType) Scan(value interface{}) error {
	if value == nil {
		ns.AccountType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.AccountType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullAccountType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.AccountType), nil
}

type CurrentNoncurrent string

const (
	CurrentNoncurrentCurrent    CurrentNoncurrent = "current"
	CurrentNoncurrentNonCurrent CurrentNoncurrent = "non_current"
)

func (e *CurrentNoncurrent) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = CurrentNoncurrent(s)
	case string:
		*e = CurrentNoncurrent(s)
	default:
		return fmt.Errorf("unsupported scan type for CurrentNoncurrent: %T", src)
	}
	return nil
}

type NullCurrentNoncurrent struct {
	CurrentNoncurrent CurrentNoncurrent `json:"current_noncurrent"`
	Valid             bool              `json:"valid"` // Valid is true if CurrentNoncurrent is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullCurrentNoncurrent) Scan(value interface{}) error {
	if value == nil {
		ns.CurrentNoncurrent, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.CurrentNoncurrent.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullCurrentNoncurrent) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.CurrentNoncurrent), nil
}

type EntrySide string

const (
	EntrySideDebit  EntrySide = "debit"
	EntrySideCredit EntrySide = "credit"
)

func (e *EntrySide) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = EntrySide(s)
	case string:
		*e = EntrySide(s)
	default:
		return fmt.Errorf("unsupported scan type for EntrySide: %T", src)
	}
	return nil
}

type NullEntrySide struct {
	EntrySide EntrySide `json:"entry_side"`
	Valid     bool      `json:"valid"` // Valid is true if EntrySide is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullEntrySide) Scan(value interface{}) error {
	if value == nil {
		ns.EntrySide, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.EntrySide.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullEntrySide) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.EntrySide), nil
}

type NormalBalance string

const (
	NormalBalanceDebit  NormalBalance = "debit"
	NormalBalanceCredit NormalBalance = "credit"
)

func (e *NormalBalance) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = NormalBalance(s)
	case string:
		*e = NormalBalance(s)
	default:
		return fmt.Errorf("unsupported scan type for NormalBalance: %T", src)
	}
	return nil
}

type NullNormalBalance struct {
	NormalBalance NormalBalance `json:"normal_balance"`
	Valid         bool          `json:"valid"` // Valid is true if NormalBalance is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullNormalBalance) Scan(value interface{}) error {
	if value == nil {
		ns.NormalBalance, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.NormalBalance.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullNormalBalance) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.NormalBalance), nil
}

type Account struct {
	ID                 uuid.UUID          `json:"id"`
	Code               int32              `json:"code"`
	Name               string             `json:"name"`
	Description        string             `json:"description"`
	Type               AccountType        `json:"type"`
	NormalBalance      NormalBalance      `json:"normal_balance"`
	Postable           bool               `json:"postable"`
	CurrentNoncurrent  *CurrentNoncurrent `json:"current_noncurrent"`
	IfrsLineItem       string             `json:"ifrs_line_item"`
	AllowedBooks       []string           `json:"allowed_books"`
	RequiredDimensions []string           `json:"required_dimensions"`
	Status             AccountStatus      `json:"status"`
	Owner              string             `json:"owner"`
}

type Book struct {
	ID   uuid.UUID `json:"id"`
	Code string    `json:"code"`
	Name string    `json:"name"`
}

type DimensionType struct {
	ID   uuid.UUID `json:"id"`
	Code string    `json:"code"`
	Name string    `json:"name"`
}

type DimensionValue struct {
	ID              uuid.UUID `json:"id"`
	DimensionTypeID uuid.UUID `json:"dimension_type_id"`
	Code            string    `json:"code"`
	Name            string    `json:"name"`
}

type IdempotencyRecord struct {
	Key            string    `json:"key"`
	OwnerSub       string    `json:"owner_sub"`
	RequestHash    string    `json:"request_hash"`
	ResponseStatus int32     `json:"response_status"`
	ResponseBody   []byte    `json:"response_body"`
	CreatedAt      time.Time `json:"created_at"`
}

type JournalEntry struct {
	ID          uuid.UUID `json:"id"`
	EntryDate   time.Time `json:"entry_date"`
	Description string    `json:"description"`
	OwnerSub    string    `json:"owner_sub"`
	BookID      uuid.UUID `json:"book_id"`
	CreatedAt   time.Time `json:"created_at"`
	UpdatedAt   time.Time `json:"updated_at"`
	Version     int32     `json:"version"`
}

type JournalLine struct {
	ID             uuid.UUID      `json:"id"`
	JournalEntryID uuid.UUID      `json:"journal_entry_id"`
	AccountID      uuid.UUID      `json:"account_id"`
	Side           EntrySide      `json:"side"`
	Amount         pgtype.Numeric `json:"amount"`
	LineNo         int32          `json:"line_no"`
}

type JournalLineDimension struct {
	ID               uuid.UUID `json:"id"`
	JournalLineID    uuid.UUID `json:"journal_line_id"`
	DimensionTypeID  uuid.UUID `json:"dimension_type_id"`
	DimensionValueID uuid.UUID `json:"dimension_value_id"`
}
