// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package query

import (
	"context"
)

type Querier interface {
	// Query-side financial statements. SELECT ONLY. Aggregates are owner-scoped and
	// grouped by CoA element (IT7). The service converts signed sums into presented
	// positive balances using each account's normal_balance.
	// net_debit = Σ(debit) − Σ(credit) per account. Asset balance = net_debit;
	// liability/equity balance = −net_debit. Assets == liabilities + equity (AT6).
	BalanceSheet(ctx context.Context, ownerSub string) ([]BalanceSheetRow, error)
	// Query-side reads. SELECT ONLY — this package is imported by cmd/query, which
	// must have NO write path (IT9). Every read is scoped by owner_sub so one
	// owner never sees another's rows (AT3, IT5).
	GetJournalEntry(ctx context.Context, arg GetJournalEntryParams) (GetJournalEntryRow, error)
	// Lines of one entry, owner-scoped via the parent entry.
	GetJournalLines(ctx context.Context, arg GetJournalLinesParams) ([]GetJournalLinesRow, error)
	// Debit/credit totals per requested account, scoped to the caller's entries.
	// LEFT JOINs keep requested accounts that have no postings (zero totals).
	GetOutstandingBalances(ctx context.Context, arg GetOutstandingBalancesParams) ([]GetOutstandingBalancesRow, error)
	// Query-side chart-of-accounts + outstanding balances. SELECT ONLY.
	ListAccounts(ctx context.Context) ([]ListAccountsRow, error)
	// Cursor pagination on the time-ordered UUIDv7 PK. A NULL cursor starts at the
	// first page; the handler asks for limit+1 rows to compute has_more.
	ListJournalEntries(ctx context.Context, arg ListJournalEntriesParams) ([]ListJournalEntriesRow, error)
	// net_credit = Σ(credit) − Σ(debit) per account. Income adds, expense subtracts;
	// netIncome = Σ net_credit over all P&L accounts (AT7).
	ProfitLoss(ctx context.Context, ownerSub string) ([]ProfitLossRow, error)
}

var _ Querier = (*Queries)(nil)
