// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: statement.sql

package query

import (
	"context"

	"github.com/shopspring/decimal"
)

const balanceSheet = `-- name: BalanceSheet :many

SELECT a.type,
       a.code,
       a.name,
       a.normal_balance,
       COALESCE(SUM(CASE WHEN jl.side = 'debit' THEN jl.amount ELSE -jl.amount END), 0)::numeric AS net_debit
FROM account a
LEFT JOIN journal_line  jl ON jl.account_id = a.id
LEFT JOIN journal_entry je ON je.id = jl.journal_entry_id AND je.owner_sub = $1
WHERE a.type IN ('asset', 'liability', 'equity')
GROUP BY a.type, a.code, a.name, a.normal_balance
ORDER BY a.code
`

type BalanceSheetRow struct {
	Type          AccountType     `json:"type"`
	Code          int32           `json:"code"`
	Name          string          `json:"name"`
	NormalBalance NormalBalance   `json:"normal_balance"`
	NetDebit      decimal.Decimal `json:"net_debit"`
}

// Query-side financial statements. SELECT ONLY. Aggregates are owner-scoped and
// grouped by CoA element (IT7). The service converts signed sums into presented
// positive balances using each account's normal_balance.
// net_debit = Σ(debit) − Σ(credit) per account. Asset balance = net_debit;
// liability/equity balance = −net_debit. Assets == liabilities + equity (AT6).
func (q *Queries) BalanceSheet(ctx context.Context, ownerSub string) ([]BalanceSheetRow, error) {
	rows, err := q.db.Query(ctx, balanceSheet, ownerSub)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []BalanceSheetRow{}
	for rows.Next() {
		var i BalanceSheetRow
		if err := rows.Scan(
			&i.Type,
			&i.Code,
			&i.Name,
			&i.NormalBalance,
			&i.NetDebit,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const profitLoss = `-- name: ProfitLoss :many
SELECT a.type,
       a.code,
       a.name,
       COALESCE(SUM(CASE WHEN jl.side = 'credit' THEN jl.amount ELSE -jl.amount END), 0)::numeric AS net_credit
FROM account a
LEFT JOIN journal_line  jl ON jl.account_id = a.id
LEFT JOIN journal_entry je ON je.id = jl.journal_entry_id AND je.owner_sub = $1
WHERE a.type IN ('income', 'expense')
GROUP BY a.type, a.code, a.name
ORDER BY a.code
`

type ProfitLossRow struct {
	Type      AccountType     `json:"type"`
	Code      int32           `json:"code"`
	Name      string          `json:"name"`
	NetCredit decimal.Decimal `json:"net_credit"`
}

// net_credit = Σ(credit) − Σ(debit) per account. Income adds, expense subtracts;
// netIncome = Σ net_credit over all P&L accounts (AT7).
func (q *Queries) ProfitLoss(ctx context.Context, ownerSub string) ([]ProfitLossRow, error) {
	rows, err := q.db.Query(ctx, profitLoss, ownerSub)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ProfitLossRow{}
	for rows.Next() {
		var i ProfitLossRow
		if err := rows.Scan(
			&i.Type,
			&i.Code,
			&i.Name,
			&i.NetCredit,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
