// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: idempotency.sql

package command

import (
	"context"
	"time"
)

const deleteExpiredIdempotency = `-- name: DeleteExpiredIdempotency :exec
DELETE FROM idempotency_record WHERE created_at < $1
`

func (q *Queries) DeleteExpiredIdempotency(ctx context.Context, createdAt time.Time) error {
	_, err := q.db.Exec(ctx, deleteExpiredIdempotency, createdAt)
	return err
}

const getIdempotencyRecord = `-- name: GetIdempotencyRecord :one

SELECT key, owner_sub, request_hash, response_status, response_body, created_at
FROM idempotency_record
WHERE key = $1 AND owner_sub = $2
`

type GetIdempotencyRecordParams struct {
	Key      string `json:"key"`
	OwnerSub string `json:"owner_sub"`
}

// Command-side idempotency records (plan 03 S8b). Scoped by (key, owner_sub).
func (q *Queries) GetIdempotencyRecord(ctx context.Context, arg GetIdempotencyRecordParams) (IdempotencyRecord, error) {
	row := q.db.QueryRow(ctx, getIdempotencyRecord, arg.Key, arg.OwnerSub)
	var i IdempotencyRecord
	err := row.Scan(
		&i.Key,
		&i.OwnerSub,
		&i.RequestHash,
		&i.ResponseStatus,
		&i.ResponseBody,
		&i.CreatedAt,
	)
	return i, err
}

const insertIdempotencyRecord = `-- name: InsertIdempotencyRecord :exec
INSERT INTO idempotency_record (key, owner_sub, request_hash, response_status, response_body)
VALUES ($1, $2, $3, $4, $5)
`

type InsertIdempotencyRecordParams struct {
	Key            string `json:"key"`
	OwnerSub       string `json:"owner_sub"`
	RequestHash    string `json:"request_hash"`
	ResponseStatus int32  `json:"response_status"`
	ResponseBody   []byte `json:"response_body"`
}

func (q *Queries) InsertIdempotencyRecord(ctx context.Context, arg InsertIdempotencyRecordParams) error {
	_, err := q.db.Exec(ctx, insertIdempotencyRecord,
		arg.Key,
		arg.OwnerSub,
		arg.RequestHash,
		arg.ResponseStatus,
		arg.ResponseBody,
	)
	return err
}
