// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: journal_entry.sql

package command

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const deleteJournalEntry = `-- name: DeleteJournalEntry :exec
DELETE FROM journal_entry WHERE id = $1 AND owner_sub = $2
`

type DeleteJournalEntryParams struct {
	ID       uuid.UUID `json:"id"`
	OwnerSub string    `json:"owner_sub"`
}

// Cascade drops journal_line + journal_line_dimension (AT5).
func (q *Queries) DeleteJournalEntry(ctx context.Context, arg DeleteJournalEntryParams) error {
	_, err := q.db.Exec(ctx, deleteJournalEntry, arg.ID, arg.OwnerSub)
	return err
}

const deleteJournalLinesByEntry = `-- name: DeleteJournalLinesByEntry :exec
DELETE FROM journal_line WHERE journal_entry_id = $1
`

func (q *Queries) DeleteJournalLinesByEntry(ctx context.Context, journalEntryID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteJournalLinesByEntry, journalEntryID)
	return err
}

const getAccountByCode = `-- name: GetAccountByCode :one
SELECT id, code, name, type, normal_balance, postable, required_dimensions
FROM account WHERE code = $1
`

type GetAccountByCodeRow struct {
	ID                 uuid.UUID     `json:"id"`
	Code               int32         `json:"code"`
	Name               string        `json:"name"`
	Type               AccountType   `json:"type"`
	NormalBalance      NormalBalance `json:"normal_balance"`
	Postable           bool          `json:"postable"`
	RequiredDimensions []string      `json:"required_dimensions"`
}

func (q *Queries) GetAccountByCode(ctx context.Context, code int32) (GetAccountByCodeRow, error) {
	row := q.db.QueryRow(ctx, getAccountByCode, code)
	var i GetAccountByCodeRow
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Name,
		&i.Type,
		&i.NormalBalance,
		&i.Postable,
		&i.RequiredDimensions,
	)
	return i, err
}

const getBookByCode = `-- name: GetBookByCode :one

SELECT id, code, name FROM book WHERE code = $1
`

// Command-side writes for journal entries. WRITE ONLY — never SELECT-for-serve
// (that lives in the query package). Reference lookups here resolve business
// keys (account code, book/dimension codes) to ids during a write tx.
func (q *Queries) GetBookByCode(ctx context.Context, code string) (Book, error) {
	row := q.db.QueryRow(ctx, getBookByCode, code)
	var i Book
	err := row.Scan(&i.ID, &i.Code, &i.Name)
	return i, err
}

const getDimensionValue = `-- name: GetDimensionValue :one
SELECT dv.id, dv.code, dt.code AS type_code
FROM dimension_value dv
JOIN dimension_type dt ON dt.id = dv.dimension_type_id
WHERE dt.code = $1 AND dv.code = $2
`

type GetDimensionValueParams struct {
	Code   string `json:"code"`
	Code_2 string `json:"code_2"`
}

type GetDimensionValueRow struct {
	ID       uuid.UUID `json:"id"`
	Code     string    `json:"code"`
	TypeCode string    `json:"type_code"`
}

func (q *Queries) GetDimensionValue(ctx context.Context, arg GetDimensionValueParams) (GetDimensionValueRow, error) {
	row := q.db.QueryRow(ctx, getDimensionValue, arg.Code, arg.Code_2)
	var i GetDimensionValueRow
	err := row.Scan(&i.ID, &i.Code, &i.TypeCode)
	return i, err
}

const getJournalEntryForUpdate = `-- name: GetJournalEntryForUpdate :one
SELECT id, owner_sub, version FROM journal_entry WHERE id = $1
`

type GetJournalEntryForUpdateRow struct {
	ID       uuid.UUID `json:"id"`
	OwnerSub string    `json:"owner_sub"`
	Version  int32     `json:"version"`
}

func (q *Queries) GetJournalEntryForUpdate(ctx context.Context, id uuid.UUID) (GetJournalEntryForUpdateRow, error) {
	row := q.db.QueryRow(ctx, getJournalEntryForUpdate, id)
	var i GetJournalEntryForUpdateRow
	err := row.Scan(&i.ID, &i.OwnerSub, &i.Version)
	return i, err
}

const insertJournalEntry = `-- name: InsertJournalEntry :one
INSERT INTO journal_entry (id, entry_date, description, owner_sub, book_id)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, version
`

type InsertJournalEntryParams struct {
	ID          uuid.UUID `json:"id"`
	EntryDate   time.Time `json:"entry_date"`
	Description string    `json:"description"`
	OwnerSub    string    `json:"owner_sub"`
	BookID      uuid.UUID `json:"book_id"`
}

type InsertJournalEntryRow struct {
	ID      uuid.UUID `json:"id"`
	Version int32     `json:"version"`
}

func (q *Queries) InsertJournalEntry(ctx context.Context, arg InsertJournalEntryParams) (InsertJournalEntryRow, error) {
	row := q.db.QueryRow(ctx, insertJournalEntry,
		arg.ID,
		arg.EntryDate,
		arg.Description,
		arg.OwnerSub,
		arg.BookID,
	)
	var i InsertJournalEntryRow
	err := row.Scan(&i.ID, &i.Version)
	return i, err
}

const insertJournalLine = `-- name: InsertJournalLine :exec
INSERT INTO journal_line (id, journal_entry_id, account_id, side, amount, line_no)
VALUES ($1, $2, $3, $4, $5, $6)
`

type InsertJournalLineParams struct {
	ID             uuid.UUID      `json:"id"`
	JournalEntryID uuid.UUID      `json:"journal_entry_id"`
	AccountID      uuid.UUID      `json:"account_id"`
	Side           EntrySide      `json:"side"`
	Amount         pgtype.Numeric `json:"amount"`
	LineNo         int32          `json:"line_no"`
}

func (q *Queries) InsertJournalLine(ctx context.Context, arg InsertJournalLineParams) error {
	_, err := q.db.Exec(ctx, insertJournalLine,
		arg.ID,
		arg.JournalEntryID,
		arg.AccountID,
		arg.Side,
		arg.Amount,
		arg.LineNo,
	)
	return err
}

const insertJournalLineDimension = `-- name: InsertJournalLineDimension :exec
INSERT INTO journal_line_dimension (journal_line_id, dimension_type_id, dimension_value_id)
SELECT $1, dt.id, dv.id
FROM dimension_type dt
JOIN dimension_value dv ON dv.dimension_type_id = dt.id
WHERE dt.code = $2 AND dv.code = $3
`

type InsertJournalLineDimensionParams struct {
	JournalLineID uuid.UUID `json:"journal_line_id"`
	Code          string    `json:"code"`
	Code_2        string    `json:"code_2"`
}

func (q *Queries) InsertJournalLineDimension(ctx context.Context, arg InsertJournalLineDimensionParams) error {
	_, err := q.db.Exec(ctx, insertJournalLineDimension, arg.JournalLineID, arg.Code, arg.Code_2)
	return err
}

const updateJournalEntryHeader = `-- name: UpdateJournalEntryHeader :one
UPDATE journal_entry
SET entry_date = $2, description = $3
WHERE id = $1 AND version = $4
RETURNING version
`

type UpdateJournalEntryHeaderParams struct {
	ID          uuid.UUID `json:"id"`
	EntryDate   time.Time `json:"entry_date"`
	Description string    `json:"description"`
	Version     int32     `json:"version"`
}

// Optimistic concurrency: only updates when the caller's version matches.
// The BEFORE UPDATE trigger bumps version + updated_at; RETURNING gives the new
// version. Zero rows affected ⇒ version conflict (handler → 409).
func (q *Queries) UpdateJournalEntryHeader(ctx context.Context, arg UpdateJournalEntryHeaderParams) (int32, error) {
	row := q.db.QueryRow(ctx, updateJournalEntryHeader,
		arg.ID,
		arg.EntryDate,
		arg.Description,
		arg.Version,
	)
	var version int32
	err := row.Scan(&version)
	return version, err
}
