// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package command

import (
	"context"
	"time"

	"github.com/google/uuid"
)

type Querier interface {
	DeleteExpiredIdempotency(ctx context.Context, createdAt time.Time) error
	// Cascade drops journal_line + journal_line_dimension (AT5).
	DeleteJournalEntry(ctx context.Context, arg DeleteJournalEntryParams) error
	DeleteJournalLinesByEntry(ctx context.Context, journalEntryID uuid.UUID) error
	GetAccountByCode(ctx context.Context, code int32) (GetAccountByCodeRow, error)
	// Command-side writes for journal entries. WRITE ONLY — never SELECT-for-serve
	// (that lives in the query package). Reference lookups here resolve business
	// keys (account code, book/dimension codes) to ids during a write tx.
	GetBookByCode(ctx context.Context, code string) (Book, error)
	GetDimensionValue(ctx context.Context, arg GetDimensionValueParams) (GetDimensionValueRow, error)
	// Command-side idempotency records (plan 03 S8b). Scoped by (key, owner_sub).
	GetIdempotencyRecord(ctx context.Context, arg GetIdempotencyRecordParams) (IdempotencyRecord, error)
	GetJournalEntryForUpdate(ctx context.Context, id uuid.UUID) (GetJournalEntryForUpdateRow, error)
	InsertIdempotencyRecord(ctx context.Context, arg InsertIdempotencyRecordParams) error
	InsertJournalEntry(ctx context.Context, arg InsertJournalEntryParams) (InsertJournalEntryRow, error)
	InsertJournalLine(ctx context.Context, arg InsertJournalLineParams) error
	InsertJournalLineDimension(ctx context.Context, arg InsertJournalLineDimensionParams) error
	// Optimistic concurrency: only updates when the caller's version matches.
	// The BEFORE UPDATE trigger bumps version + updated_at; RETURNING gives the new
	// version. Zero rows affected ⇒ version conflict (handler → 409).
	UpdateJournalEntryHeader(ctx context.Context, arg UpdateJournalEntryHeaderParams) (int32, error)
}

var _ Querier = (*Queries)(nil)
